language: bash

sudo: required
services:
  - docker

script:
  - docker build -t boot2docker/boot2docker .
  - docker run --rm boot2docker/boot2docker > boot2docker.iso

after_script:
  - docker images
  - ls -l *.iso

# vim:set et ts=2 sw=2:
